# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: learnandearn
# "service" is the name of this project. This will also be added to your AWS resource names.
service: demofunctions

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:905418112354:table/Todotable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          path: /addtodo
          method: post
#infrastrcture provisoing
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Todotable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
