# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: learnandearn
# "service" is the name of this project. This will also be added to your AWS resource names.
service: demofunctions

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
#infrastrcture provisoing
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Todotable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
